### ISSUE TITLE
could you add two more features?

### ISSUE THREAD

**Issue by Fqmane** [womblee/microphone_toggler#2]
first of all, i fucking love your programm. It's simple and it doesn't consume a lot of memory and it works perfectly

personally, i ran into two issues:

i can't have CTRL+SHIFT+ALT combo as a hotkey without main keys, i have to add something else. Is there a way to make CTRL+SHIFT+ALT a hotkey?

the second issue is that i have to reload config everytime i restart the program. can you make it so that it reloads config everytime it starts?

thanks a lot guys!! your program is the most convinient i've seen, don't make it weirder

**Comment by womblee** [comment]
Thanks for the feedback! Glad you're enjoying the program.

Issue #1 - CTRL+SHIFT+ALT combo without main key:
Unfortunately, this isn't possible due to Windows limitations. The hotkey system requires a specific key press (like F1, A, Space, etc.) with optional modifiers. Modifiers alone can't trigger a hotkey because Windows can't detect when "all three are pressed" as a complete action versus just being held down. You'll need to add at least one main key to your combination.

Issue #2 - Config not reloading on restart:

Fixed! The updated code now:
Always loads config on startup (it did before, but now more reliably)
Uses absolute paths so config files are always found in the same directory as the .exe, regardless of where you run it from

**Comment by Fqmane** [comment]
still doesnt work, idk what's the issue here. BUT THANK YOU !!!!
config not being loaded is not a big problem, so i'm fine with that
thanks a lot!!
